context:
  session: concert_sim
  params:
    hw_type: sim

xbot2:
  cmd: xbot2-core --hw {hw_type}
  ready_check: timeout 5 ros2 topic echo --once /xbotcore/joint_states
  depends: [gazebo]
  variants:
    ctrl:
      - sim:
          params:
            hw_type: sim
      - dummy:
          params:
            hw_type: dummy
